# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
- master

pool:
  vmImage: 'ubuntu-latest'
strategy:
  matrix:
    Python37:
      python.version: '3.7'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    pytest
  displayName: 'pytest'
- task: InvokeRESTAPI@1
  inputs:
    connectionType: 'connectedServiceName'
    serviceConnection: 'generic-api'
    method: 'PATCH'
    headers: |
      {
      "Content-Type":"application/json-patch+json", 
      "PlanUrl": "$(system.CollectionUri)", 
      "ProjectId": "$(system.TeamProjectId)", 
      "HubName": "$(system.HostType)", 
      "PlanId": "$(system.PlanId)", 
      "JobId": "$(system.JobId)", 
      "TimelineId": "$(system.TimelineId)", 
      "TaskInstanceId": "$(system.TaskInstanceId)", 
      "AuthToken": "$(system.AccessToken)"
      }
    body: |
      [
        {
          "op": "replace ",
          "path": "/rev",
          "value": 16
        },
        {
          "op": "replace",
          "path": "/fields/WEF_F6F7CD2995A6447DA4C12DDAFAFBCB9D_Kanban.Column.Done",
          "value": "true"
        }
      ]
    urlSuffix: '/wit/workitems/400655?api-version=5.1'
    waitForCompletion: 'false'